# Generated by Django 6.0.7 on 2026-08-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feature_1', models.CharField(max_length=20)),
                ('feature_2', models.CharField(max_length=20)),
                ('feature_3', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
