# Generated by Django 6.0.7 on 2026-08-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFuncts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='feature_1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='services',
            name='feature_2',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='services',
            name='feature_3',
            field=models.CharField(max_length=80),
        ),
    ]
